### PR TITLE
Fix cards Ui 

### PR DESCRIPTION
**Pull request by shubhagarwal1**
fix: #122 
Screenshot 2024-10-19 at 10 44 56 PM
hey @TejasNasre

### CODE REVIEW

**Comment by TejasNasre** [comment]
Bro how you are adding event without image there it's creat bugs later

**Comment by shubhagarwal1** [comment]
> Bro how you are adding event without image there it's creat bugs later

I tried to create event but due to wrong db setup i was stuck on the point 
so in order to complete the task i just manged to create the event, that's it 
also it will not create any bug because i have added changes to only one file that is event card file.
also i have requested you to connect, can we please connect so that this problem of mine could get solved

**Comment by TejasNasre** [comment]
join vc gssoc

**Comment by NEGRAH-S** [comment]
@MastanSayyad , very minimalistic changes should be classified as Level 1

**Comment by shubhagarwal1** [comment]
> @MastanSayyad , very minimalistic changes should be classified as Level 1

Hey @NEGRAH-S i truely respect the review for PRs, it is my humbel request please dont judge the additions on the basis of number of lines added or color chnges these changes also take lot of efforsts. Hope you understand. Please guide me if there are more things to mention.

**Comment by NEGRAH-S** [comment]
@shubhagarwal1 , Yes I understand being a developer myself and a GSoC'24 contributor. If UI changes had any components changed It would have been a level2 but since you only changed css styling it would be considered as level1.

**Review by MastanSayyad — COMMENTED** [review]
As per @NEGRAH-S only few css changes have been made

**Pull request merged**
