### PR TITLE
Update::Implement Form Validation, Dashboard Redirection, and Remove Unused Forms Folder (For Event Feedback)

### PR DESCRIPTION
**Pull request by 0xPratikPatil**
Form Validation (100 characters limit) ✅
Redirection to Dashboard ✅
Removing the Forms Folder ✅

### CODE REVIEW

**Comment by TejasNasre** [comment]
you missed one update sir the btn should not be disable the btn should work initially but if user not logged in then it should send toast to login first

**Comment by TejasNasre** [comment]
update this PR

**Comment by TejasNasre** [comment]
no update mehul sir ne kar deya hai

**Comment by TejasNasre** [comment]
open karo bhai PR

**Comment by TejasNasre** [comment]
join vc

**Comment by 0xPratikPatil** [comment]
I am traveling. Is there anything you need or any task you want to assign? Also, I didn't get the points for this PR.

**Comment by TejasNasre** [comment]
sir ji online ho abhi vc me join karna gssoc

**Pull request merged**
