### PR TITLE
Added transition in stats

### PR DESCRIPTION
**Pull request by haseebzaki-07**
This PR is modified for #84 

@TejasNasre is this fine now?

### CODE REVIEW

**Comment by TejasNasre** [comment]
err

**Comment by TejasNasre** [comment]
@haseebzaki-07 i told you to run : npm run build now update the PR don't raised another

**Comment by haseebzaki-07** [comment]
hey @TejasNasre please check now also I was getting a error related to one of the APIs

Screenshot 2024-10-13 220533

**Comment by TejasNasre** [comment]
@haseebzaki-07 Thanks For Contribution 😀

**Comment by haseebzaki-07** [comment]
@TejasNasre thank you

**Pull request merged**
