### PR TITLE
Added a button to save events to google calendar

### LINKED ISSUE #32: add events to the gogle calendar
add event to google calendar after click to save event to google calendar after user register for event

### PR DESCRIPTION
**Pull request by mehul-m-prajapati**
fixes #32

Animation4

### CODE REVIEW

**Comment by TejasNasre** [comment]
sir the btn should visible after user register for specific use and we need any api key to integrate this thing ?

**Comment by mehul-m-prajapati** [comment]
I don't think we need api key. On which page, do you want this button? @TejasNasre

**Comment by TejasNasre** [comment]
> I don't think we need api key. On which page, do you want this button? @TejasNasre

Same page but when user is regarding for that specific event then need small change there in code fix it

**Comment by mehul-m-prajapati** [comment]
@TejasNasre : okay, updated the code.
- Conditionally Enable the Button: The onClick event handler for the button is set to undefined if the user is not registered, effectively disabling it.

**Comment by TejasNasre** [comment]
tt
sir don't show btn. if the user is not register for the event then don't show the btn and fix this also 
hh
the event is inactive still showing btn the code is written but its a bug there please fix it

**Comment by mehul-m-prajapati** [comment]
@TejasNasre : okay, I will disable those 2 buttons if event is inactive

**Pull request merged**
