### PR TITLE
Added SortByPrice Functionality | Issue #1689

### PR DESCRIPTION
**Pull request by Shariq2003**
I have added the sort by price functionality in the Events.

https://github.com/user-attachments/assets/b02393c7-a6ca-4f01-8222-95492983dc7a

Completed #169

### CODE REVIEW

**Comment by TejasNasre** [comment]
Screenshot_2024-10-25-09-25-19-15

**Comment by TejasNasre** [comment]
@Shariq2003 fix this broo

**Comment by Shariq2003** [comment]
> @Shariq2003 fix this broo

Yes @TejasNasre sir, I will definitely fix this, I am currently in college

**Comment by Shariq2003** [comment]
Will fix this asap after college off

**Comment by Shariq2003** [comment]
@TejasNasre sir, please check again

**Comment by TejasNasre** [comment]
priceerror
fix it ser

**Comment by TejasNasre** [comment]
errrrr

**Comment by Shariq2003** [comment]
@TejasNasre Build compile successfully on Local, please check on Vercel now

image

**Comment by Shariq2003** [comment]
@TejasNasre please check deployment its fine now,
Please merge this.

**Comment by TejasNasre** [comment]
change branch to dev i will merge

**Comment by Shariq2003** [comment]
> change branch to dev i will merge

okay

**Pull request closed without merging**
