### PR TITLE
Contact Us page Added

### PR DESCRIPTION
**Pull request by Ahsankhalid618**
#45 
 A new Contact Form was added, Full functionality was implemented, Supabase integration for feedback, Email functionality with Resend was implemented for Feedback, and a map was added to the Contact Page.

### CODE REVIEW

**Comment by TejasNasre** [comment]
the seo thing you changed i think there should be you production url not localhost correct me if i am wrong

**Comment by Ahsankhalid618** [comment]
Yes, My bad, It can be edited within the github repo, or I can change that and make PR again. Whatever is suitable to you, what you say?

**Comment by TejasNasre** [comment]
> Yes, My bad, It can be edited within the github repo, or I can change that and make PR again. Whatever is suitable to you, what you say?

change in local then commit and add the commit to this pr don't need to make new or you can change on github it self if you want

**Comment by TejasNasre** [comment]
> @TejasNasre Updated the robot.txt file
> 
> > > Yes, My bad, It can be edited within the github repo, or I can change that and make PR again. Whatever is suitable to you, what you say?
> > 
> > 
> > change in local then commit and add the commit to this pr don't need to make new or you can change on github it self if you want

Update the sitemap bro and upadte and update ho raha hai no need of new pr

**Comment by Ahsankhalid618** [comment]
> > @TejasNasre Updated the robot.txt file
> > > > Yes, My bad, It can be edited within the github repo, or I can change that and make PR again. Whatever is suitable to you, what you say?
> > > 
> > > 
> > > change in local then commit and add the commit to this pr don't need to make new or you can change on github it self if you want
> 
> Update the sitemap bro and upadte and update ho raha hai no need of new pr

I have updated the sitemaps and rebuilt the project successfully, Just committed the changes to this PR. Check it, please.

**Comment by TejasNasre** [comment]
I will merge it I am getting conflict I will resolve them merge

**Comment by Ahsankhalid618** [comment]
👍 okay

**Pull request merged**
