### PR TITLE
Implementation For Request Booking At Event Space

### LINKED ISSUE #49: Implementation For Request Booking At Event Space
We have event space at dashboard then explore events and under that request booking for the space i made the schema for supabase check LEARN.md you just need to make the form and run insert query on it.

Make PR to dev and post video before make PR

### PR DESCRIPTION
**Pull request by rudrapratap63**
Fix #49 

check the walkthrough video : 

https://github.com/user-attachments/assets/f8152cff-2339-4d23-8b7a-a08f8a1f7f18

### CODE REVIEW

**Comment by rudrapratap63** [comment]
@TejasNasre , please check the PR and If you would like any other changes, let me know.

**Comment by rudrapratap63** [comment]
@TejasNasre  , please check the PR. I have now redirected the user to the dashboard when they click the request-booking button.

**Comment by TejasNasre** [comment]
src/app/(event-space)/explore-event-space/[spaceId]/page.tsx here why you are wrote redirection link like this router.push(`/explore-event-space/request-booking?spaceId=${spaceId}`);  just write router.push(`/register-event/${spaceId}`); is there any difference ?  and the data your are taking don't show sapceId in form and organizerId take organiserId will be email we just need date and submit btn the status will be update by admin

**Comment by TejasNasre** [comment]
update the things here i will merge it soon

**Comment by rudrapratap63** [comment]
@TejasNasre , the routes` router.push(/explore-event-space/request-booking?spaceId=${spaceId})` and `router.push(/register-event/${spaceId})` are different. If we redirect the user to` /register-event/${spaceId}`, they will be taken to this page:

image

On the other hand, for the "request event space" functionality, I have created a new page:
image

If I'm mistaken, please correct me.

**Comment by rudrapratap63** [comment]
> and the data your are taking don't show sapceId in form and organizerId take organiserId will be email we just need date and submit btn the status will be update by admin

Could you please explain this in more detail? I'm feeling a bit confused.

**Comment by TejasNasre** [comment]
> @TejasNasre , the routes` router.push(/explore-event-space/request-booking?spaceId=${spaceId})` and `router.push(/register-event/${spaceId})` are different. If we redirect the user to` /register-event/${spaceId}`, they will be taken to this page:
> 
> image
> i know i am talking about format '/explore-event-space/request-booking/{id}`

**Comment by TejasNasre** [comment]
> On the other hand, for the "request event space" functionality, I have created a new page: image
> 
> If I'm mistaken, please correct me.
 here take only date and submit the organizerid is email don't post actual id and email will fetched directly with use details right but add with id don't show there

**Comment by TejasNasre** [comment]
any updates

**Comment by rudrapratap63** [comment]
Hi @TejasNasre  , I apologize for the delay. I had a fever, which slowed down my progress. However, I’m feeling better now and will update the PR and complete my work today.

**Comment by TejasNasre** [comment]
> Hi @TejasNasre , I apologize for the delay. I had a fever, which slowed down my progress. However, I’m feeling better now and will update the PR and complete my work today.

yeah no worries

**Comment by rudrapratap63** [comment]
@TejasNasre  Please check: I have removed the organiser ID input and now use the organiser's email for the ID. Additionally, I have removed the spaceId and status inputs, set the status to 'pending,' which will be approved by the admin.

image

In supabase value stored like this:
image

**Comment by TejasNasre** [comment]
great post video with working db and this frontend and add info to Learn.md i will merge it soon

**Comment by rudrapratap63** [comment]
@TejasNasre okay i will do it 👍

**Comment by rudrapratap63** [comment]
@TejasNasre, could you please advise on what should be included in the learn.md? Also, please review the video below that shows the frontend and the working database:

https://github.com/user-attachments/assets/a51afb53-85de-44a4-bb1f-5a646f022c6a

**Comment by rudrapratap63** [comment]
@TejasNasre Sir, please review the PR. I don't believe it's necessary to update the learn.md file, as I haven't made any changes that would require it. However, if you think any updates are needed, please let me know.

**Comment by TejasNasre** [comment]
all good we already have definition language no need to change anything i will merge

**Comment by rudrapratap63** [comment]
@TejasNasre Sir, if you have any other contribution tasks for me, please let me know.

**Comment by TejasNasre** [comment]
> @TejasNasre Sir, if you have any other contribution tasks for me, please let me know.

Thanks for contribution, we have lot of issues or you can make meaningful issues

**Comment by rudrapratap63** [comment]
@TejasNasre Sir, if you have any other issue in mind, then could you please suggest some Level 3 issues for my next contribution?

**Comment by TejasNasre** [comment]
> @TejasNasre Sir, if you have any other issue in mind, then could you please suggest some Level 3 issues for my next contribution?

Yeah we need new feature that If you add your own event it should require admin approve the event will show in explore page if you can solve this go ahead

**Comment by TejasNasre** [comment]
By this the Spam event will not there and in production it will help us to authenticate the event

**Pull request merged**
