### PR TITLE
Added Super admin page to approve/reject events

### LINKED ISSUE #110: Add approval button for super admin to approve/reject events
Currently, the NexMeet platform allows event organizers to submit events for listing. However, there is no mechanism for a super admin to approve or reject these submitted events. Implementing an approval button will enhance the event management workflow, ensuring that only vetted events are published on the platform.

**Objective**: To introduce an approval system for super admins that allows them to review submitted events and make decisions on their publication.

**Approval Button:**
Add an "Approve" and "Reject" button on the event submission review page accessible to super admins.

### PR DESCRIPTION
**Pull request by mehul-m-prajapati**
closes #110

- [x] Used Kinde NextJS SDK to get "events:approve" permission
- [x] Created super admin page
- [x] Updated event_details database based on approve/reject status

**NOTE:** You need to add Super Admin role with events:approve permission in your KINDE account.

### Super Admin Page
Animation4

---

### Explore events Page
Animation4

### CODE REVIEW

**Comment by TejasNasre** [comment]
need to connect once

**Comment by TejasNasre** [comment]
join vc

**Comment by mehul-m-prajapati** [comment]
@TejasNasre : Updated screenshots

**Comment by TejasNasre** [comment]
Sir vc at 11

**Pull request merged**
