### PR TITLE
Dynamic Form Added

### PR DESCRIPTION
**Pull request by 0xPratikPatil**
if it works then take a look at these tables and add it in LEARN.md

-- Create feedback_forms table
CREATE TABLE feedback_forms (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    title TEXT NOT NULL,
    created_by TEXT NOT NULL,
    event_id UUID,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create form_fields table
CREATE TABLE form_fields (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    form_id UUID NOT NULL,
    field_type TEXT NOT NULL,
    label TEXT NOT NULL,
    options JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT fk_form
        FOREIGN KEY(form_id) 
        REFERENCES feedback_forms(id)
);

-- Create form_responses table
CREATE TABLE form_responses (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    form_id UUID NOT NULL,
    respondent_email TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT fk_form
        FOREIGN KEY(form_id) 
        REFERENCES feedback_forms(id)
);

-- Create response_fields table
CREATE TABLE response_fields (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    response_id UUID NOT NULL,
    field_id UUID NOT NULL,
    value TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT fk_response
        FOREIGN KEY(response_id) 
        REFERENCES form_responses(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_field
        FOREIGN KEY(field_id) 
        REFERENCES form_fields(id)
        ON DELETE CASCADE
);

### CODE REVIEW

**Comment by TejasNasre** [comment]
@0xPratikPatil the backend architecture in incorrect bro for this feedback form

**Comment by TejasNasre** [comment]
and how to share the feedback form to others there is link specify

**Comment by 0xPratikPatil** [comment]
@TejasNasre 
Currently, there are no features for sharing the form with others. The check response button in the table is for the organizer to review submitted feedback, as I was unable to add the option to download responses in CSV or other formats in time. Please explain the new features you want to add, and I’ll open issues and try to implement them.

**Comment by TejasNasre** [comment]
the form should be share to any one and display when event gets inactive , if we don't have share option like google forms shares there how the users add the feedback and the backend architecture is in correct 
hhhh
dddd

feedback_form table not needed and others are not correct think that you have 1 lakh users the whole Db will pollute

**Comment by 0xPratikPatil** [comment]
@TejasNasre 
Could you elaborate? I didn't understand you.🥲

**Comment by TejasNasre** [comment]
you have GSSOC discord ? we will discuss there at 8.30

**Comment by 0xPratikPatil** [comment]
I am traveling can we do it at 9 pm

**Comment by TejasNasre** [comment]
> I am traveling can we do it at 9 pm

okay

**Comment by TejasNasre** [comment]
Join discord general gssoc

**Comment by TejasNasre** [comment]
@0xPratikPatil you are working that i told you that day ?
make issues i will assign you

**Comment by 0xPratikPatil** [comment]
Yes @TejasNasre,I will open issues and make pr.

**Pull request merged**
