### PR TITLE
Added MultiLang | Issue #166

### PR DESCRIPTION
**Pull request by Shariq2003**
Added Multi Lang Support

https://github.com/user-attachments/assets/9744fe70-a8d0-44d6-8f8b-27930380ad68

Completed #166

### CODE REVIEW

**Comment by TejasNasre** [comment]
Make that drop down fix in footer I think you understand what I am talking

**Comment by Shariq2003** [comment]
> Make that drop down fix in footer I think you understand what I am talking

Yup, got it

**Comment by TejasNasre** [comment]
> @TejasNasre sir, VC ?

At 11

**Comment by Shariq2003** [comment]
> > @TejasNasre sir, VC ?
> 
> At 11

okay

**Comment by TejasNasre** [comment]
Sir update ?

**Comment by Shariq2003** [comment]
> Sir update ?

@TejasNasre making it sticky to the footer is not possible due to restricted access with this script.
so we have to compromise a bit with this.

Well, it is looking good at all, a modern floating multi-lang button.

**Comment by TejasNasre** [comment]
sir solution nikaloo chatgpt karo the ux experience is not good

**Comment by Shariq2003** [comment]
> sir solution nikaloo chatgpt karo the ux experience is not good

> sir solution nikaloo chatgpt karo the ux experience is not good

okay sir

**Comment by TejasNasre** [comment]
sir kuch solution nikla

**Comment by Shariq2003** [comment]
> sir kuch solution nikla

@TejasNasre i will definitely fix this, please allow me some time to just get ride of backlogs, I make sure to complete this.

**Comment by TejasNasre** [comment]
bhai ny hua kya fix i will close this issue now and assign it to other

**Pull request closed without merging**
