### PR TITLE
build contact page

### PR DESCRIPTION
**Pull request by SumitSahu44**
i build a responsive contact page with same website color theme

### CODE REVIEW

**Comment by TejasNasre** [comment]
Before merge you should Always show output bro the ui is not good

**Comment by TejasNasre** [comment]
You just added Static ui

**Comment by SumitSahu44** [comment]
> You just added Static ui

Yes i worked on static if its compulsory then i can do backend also

**Comment by TejasNasre** [comment]
Yeah connect with backend and also make ui beautiful you just added the contact page make something cool with more info and remove the closed pr

**Comment by SumitSahu44** [comment]
@TejasNasre can you tell me exact what you are expecting from this issue

**Comment by TejasNasre** [comment]
https://github.com/TejasNasre/nexmeet/issues/11#issuecomment-2387614764

**Comment by TejasNasre** [comment]
Any Updates ?

**Comment by SumitSahu44** [comment]
it the UI of the contact page is good

**Comment by TejasNasre** [comment]
> it the UI of the contact page is good

nope

**Pull request closed without merging**
