### PR TITLE
Added comment section in event page

### LINKED ISSUE #109: Add comment section below event description
Adding Comment Section Under The Events

### PR DESCRIPTION
**Pull request by mehul-m-prajapati**
Animation2

--
fixes #109

### CODE REVIEW

**Comment by TejasNasre** [comment]
sir make new card you are adding that in info card also the ui is is not looking like comment section add by whom the comment written and when

**Comment by mehul-m-prajapati** [comment]
> sir make new card you are adding that in info card also the ui is is not looking like comment section add by whom the comment written and when

@TejasNasre : Using card for comment section and added comment table as well.

**Comment by TejasNasre** [comment]
Please post working video sir I will merge it

**Comment by mehul-m-prajapati** [comment]
@TejasNasre ; check in 1st comment. I replaced the video

**Comment by TejasNasre** [comment]
Sir jee ui ? And I told you to make new card

**Comment by mehul-m-prajapati** [comment]
I thought existing card is good enough for this comment section. 
Alright then I will make a brew card for comment @TejasNasre

**Comment by TejasNasre** [comment]
IMG_20241016_190044

**Comment by TejasNasre** [comment]
Yeah update it I will merge

**Comment by mehul-m-prajapati** [comment]
@TejasNasre : Added card for comment.

Animation4

**Comment by TejasNasre** [comment]
sir Keep in mind that you want to make PR to my dev branch i am merging now thanks from contribution

**Comment by TejasNasre** [comment]
security


sir je thoda secure code likhe anyone can comment here without login in website

**Comment by mehul-m-prajapati** [comment]
> security
> 
> sir je thoda secure code likhe anyone can comment here without login in website

@TejasNasre : I will raise an issue for this and fix it, thanks

**Pull request merged**
