### PR TITLE
Nextmeet fikir

### PR DESCRIPTION
**Pull request by fmwalle**
here is the change sir. Thank you!

### CODE REVIEW

**Comment by fikirWalle** [comment]
I’ve created a pull request (PR) for the project, and it triggered an automatic deployment on Vercel. 
Please let me know if there’s anything I need to do from my side to help with the process.

**Comment by jassBawa** [comment]
@fikirWalle please make a issue and then link this pr to that issue. So its easy for everyone to understand what you are working on.

**Comment by TejasNasre** [comment]
@soham-khedkar review this i thinks its not good ui check it and let me know

**Comment by TejasNasre** [comment]
@fikirWalle wait till soham reviewed

**Comment by soham-khedkar** [comment]
@TejasNasre give access to preview on nexmeetup@gmail.com

**Comment by TejasNasre** [comment]
> @TejasNasre give access to preview on [nexmeetup@gmail.com](mailto:nexmeetup@gmail.com)

check now

**Comment by soham-khedkar** [comment]
@TejasNasre yeah exactly ui looks weird this is not the changes I asked for faq looks weird and footer she centered everything lol I just asked logo above that text to be centred

**Comment by fikirWalle** [comment]
@soham-khedkar What makes it weird is the way you explained it. This is how I understand it.

**Comment by soham-khedkar** [comment]
@fikirWalle chill 😂 I am not judging it just a review @TejasNasre has the rights to merge it . And my bad if I couldn't explain it properly

**Comment by TejasNasre** [comment]
We can fix it bruh just a ui

**Pull request closed without merging**
