### PR TITLE
feat: added google maps integration

### LINKED ISSUE #206: Maps API integration when choosing event location
c2

### PR DESCRIPTION
**Pull request by jassBawa**
fixes #206 

## Note
1. Configure google maps api in console.google.com
2. Enable maps api and places api.
3. check env.example for reference to variable.

image

### CODE REVIEW

**Comment by jassBawa** [comment]
@TejasNasre please review this also I think we need to update the update-event thing with same functionality.

**Comment by TejasNasre** [comment]
Sir but it's giving only the city names we need exact adress, suppose we have event in some co working space so I will not adding there only specific city .I will add whole adress how the participants know the location

**Comment by jassBawa** [comment]
@TejasNasre sorry I got it wrong is this what you were expecting. ?
image

**Comment by TejasNasre** [comment]
> @TejasNasre sorry I got it wrong is this what you were expecting. ? 

yes

**Pull request merged**
