### PR TITLE
Add to Google Calendar Feature Implementation

### PR DESCRIPTION
**Pull request by ParasY1724**
**Issue No:** #32 

**Description:**
After user registered for event , Add event to google calendar option is shown.For First Time it will ask for authorization otherwise direct add by one click !!

# Note .env
Add 
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=

# How to get them ?
Check this (Till 10:00): https://www.youtube.com/watch?v=c2b2yUNWFzI 

# Note : Redirect URL and Authorization URL are Important to filled.

4. Get your credentials:
   - Add scopes :
Screenshot From 2024-10-09 23-31-34
   - After creating the OAuth client ID, you'll see a modal with your client ID and client secret
   - Copy these values and store them securely
   - Set them as environment variables in your project:
   -
     ```
     GOOGLE_CLIENT_ID=your_client_id_here
     GOOGLE_CLIENT_SECRET=your_client_secret_here
     ```

#Note to all user to access this you need to publish

# Video
1. For First Time :

https://github.com/user-attachments/assets/9f801918-5294-4d47-8e8f-9b2ef926d4a0

2.

https://github.com/user-attachments/assets/51c7b892-c9c0-48ea-9688-eb5b7114e97d

### CODE REVIEW

**Comment by ParasY1724** [comment]
Note You need to publish OAuth consent screen so not only test user can use it , everyone can.
Screenshot From 2024-10-09 23-41-58

**Comment by TejasNasre** [comment]
After reviewing I will get back to issue

**Comment by TejasNasre** [comment]
great you solved issue but the thing is that why you are adding auth to add calendar the user already registered into website this will not work remove the auth thing and also give that option in event page by which the user can add anytime he wants

**Comment by TejasNasre** [comment]
you are registering multiple times by shingle role but in productions it won't happen you can register only one time by one account i don't know why its happening

**Comment by TejasNasre** [comment]
@ParasY1724 any updates ?

**Comment by TejasNasre** [comment]
@ParasY1724 any updates ?

**Comment by TejasNasre** [comment]
@ParasY1724 any updates ?

**Pull request closed without merging**
