### PR TITLE
Hi @TejasNasre i have implemented the logo in the navbar section.

### PR DESCRIPTION
**Pull request by Nvntdad**
i have implemented the logo in the navbar section, check and merge if you liked it.
#20 
.
.
.
nxmtt
updnxmt

### CODE REVIEW

**Comment by TejasNasre** [comment]
make PR dev bro

**Comment by TejasNasre** [comment]
great logo @Nvntdad can you please send me copy on nexmeet@gmail.com we want to make more things like banner

**Comment by TejasNasre** [comment]
https://raw.githubusercontent.com/TejasNasre/nexmeet/refs/heads/main/public/logo.png want to change this

**Comment by Nvntdad** [comment]
i already raised PR for this

**Comment by TejasNasre** [comment]
Make PR to dev branch you have raised to main branch

**Comment by Nvntdad** [comment]
okay 0kay i closing this

**Pull request closed without merging**
