### PR TITLE
Toggle Theme

### PR DESCRIPTION
**Pull request by inkerton**
This is in response to the issue #52 .

https://github.com/user-attachments/assets/13e76a8c-11e9-4f8a-9b4d-4dee7c6b7845

### CODE REVIEW

**Comment by inkerton** [comment]
image

@TejasNasre

**Comment by TejasNasre** [comment]
@inkerton the issue is ui/ux enhancement so make the whole website change the color light and dark  after that in light theme add whitish creamy color not the whole white corresponding change the whole website its level 3 issue

**Comment by inkerton** [comment]
https://github.com/user-attachments/assets/5ab034e4-fa97-4989-a8e0-7b2cdc813387

The state is being saved and all pages are changing theme if there is any page which is not changing theme then let me know I will see for any issue.

**Comment by TejasNasre** [comment]
you are updating other changes ?

**Comment by inkerton** [comment]
> you are updating other changes ?

Konse other changes bhai toggle button and start vala tha daal diya vo maine and koi issue ya khin problem h toh do let me know . Mujhe genuinely smjh nhi aaya what other changes are you talking about.

Global state is being saved . Theme is applied to the whole website is alawa kya changes the?

**Comment by TejasNasre** [comment]
ui1
should show the star count here the ui not good
ui2
were are the borders and the event card should text white after open details page the borders are not there
ui3
border are not there

**Comment by TejasNasre** [comment]
@inkerton i think you are ui/ux enthusiast so rewrap the whole components 😀add your creativity

**Comment by inkerton** [comment]
Yeah I did not add any env variables so I could not check these pages. By any chance can you provide me with the env variable values?
@TejasNasre

**Comment by TejasNasre** [comment]
Make upadtes asap with all changes its level 3 issue you don't need to add any Functionality and work with backend things just adding you do it fast 😄

**Comment by inkerton** [comment]
> Make update asap with all changes its level 3 issue you don't need to add any Functionality and work with backend things just adding you do it fast 😄

Working on it will do it in an hour

**Comment by inkerton** [comment]
https://github.com/user-attachments/assets/151e4a79-639a-42fb-ba57-dbe8c14b22ea


@TejasNasre Done all completed

**Comment by TejasNasre** [comment]
i am merging it but with level2. Thanks for your contribution

**Comment by TejasNasre** [comment]
res
please write code that covers all the edge cases here the ui breaks at mobile device

**Comment by inkerton** [comment]
Can You make It a another issue I will adjust the Button . You can make It a level 1 issue . I'll do it right away.

**Comment by TejasNasre** [comment]
> Can You make It a another issue I will adjust the Button . You can make It a level 1 issue . I'll do it right away.

please update here

**Comment by TejasNasre** [comment]
or don't update now whole ui thing will fix later need to add functionality first

**Comment by inkerton** [comment]
k let me know when you need it

**Pull request merged**
