### PR TITLE
Added zod validation for all fields in Update Event Page

### LINKED ISSUE #151: Bugs : In Update Event
When We Go For Event Updating There Are Bugs : 

wrong data
 
getting wrong date in registration end and start also in event start and end the date picker is buggy selecting any date.

contact

in contact the words are allowed fix

negative price

negative price section 

pop up
  
the ui is not good in pop up

### PR DESCRIPTION
**Pull request by mehul-m-prajapati**
Zod validation to the event update form in the UpdateEvent component. The key changes and features included in this update are:

### Zod Schema Definition:

- A comprehensive Zod schema (eventSchema) has been defined to validate the event data. This ensures that all required fields are properly filled out and that they meet specific criteria (e.g., non-empty strings, valid URLs, numeric values for duration and price).
- The schema also includes custom error messages for improved user feedback.

### Form Data Validation:
- Before the event is updated in the database, the event data is validated against the Zod schema. If the validation fails, error messages are displayed to the user, indicating what needs to be corrected.
Animation2

Fixes #151

### CODE REVIEW

**Comment by TejasNasre** [comment]
sir add description

**Comment by mehul-m-prajapati** [comment]
@TejasNasre : I will add it.. It is still work in progress

**Comment by TejasNasre** [comment]
sir vc ?

**Comment by mehul-m-prajapati** [comment]
@TejasNasre : Added screenshot and description.

**Pull request merged**
