### PR TITLE
Added buttons in nav bar & options in profile dropdown

### LINKED ISSUE #146: Replace text with buttons in nav bar and add profile drop-down menu

### PR DESCRIPTION
**Pull request by mehul-m-prajapati**
fixes #146

Animation4

### CODE REVIEW

**Comment by TejasNasre** [comment]
join vc gssoc

**Comment by TejasNasre** [comment]
https://artificix.onrender.com/ update the navlink border on hover and add ativeness on active page visit

**Comment by TejasNasre** [comment]
sir connect ho skate hai added level 2

**Comment by mehul-m-prajapati** [comment]
What changes are you suggesting now?

**Comment by TejasNasre** [comment]
need to connect once

**Comment by mehul-m-prajapati** [comment]
@TejasNasre : I have added animation effects.
Animation5

**Pull request merged**
