### PR TITLE
Updated twitter logo

### PR DESCRIPTION
**Pull request by vedhcet-07**
Sir this issue was simple , but not assigned to me nor anyone . Since it was simple i rectified and directly submitted PR . 

Sir if everything is correct please accept it under gssoc and hacktoberfest . If any changes let me know . 

Thank you

### CODE REVIEW

**Comment by TejasNasre** [comment]
its not correct way to make the PR bro your are not assigned the issue still make PR and the useless issue i think you are contributing  first time its okay but don't do this stuff in other project

**Comment by vedhcet-07** [comment]
> its not correct way to make the PR bro your are not assigned the issue still make PR and the useless issue i think you are contributing first time its okay but don't do this stuff in other project

First of all sorry sir . Yea its my first time . Ok i get it its a useless issue , but i though thought it matters , i accept it its my mistake. I will make sure that I wont repeat the same in other projects . 

Thank you

**Comment by TejasNasre** [comment]
change the logo in  https://nexmeet-lake/explore-events/a97133a9-5e03-49e3-aff3-6604bed83fdb share btn then i will merge

**Comment by vedhcet-07** [comment]
> change the logo in explore-events/a97133a9-5e03-49e3-aff3-6604bed83fdb share btn then i will merge

ok sir i am checking into it . Thanks for giving a opportunity

**Comment by vedhcet-07** [comment]
> change the logo in explore-events/a97133a9-5e03-49e3-aff3-6604bed83fdb share btn then i will merge

Boss i have figured it out and pls review it . Let me know if anything . Thank you

**Comment by TejasNasre** [comment]
> > change the logo in explore-events/a97133a9-5e03-49e3-aff3-6604bed83fdb share btn then i will merge
> 
> Boss i have figured it out and pls review it . Let me know if anything . Thank you

run : npm run build the deployment got errors

**Comment by vedhcet-07** [comment]
> > > change the logo in explore-events/a97133a9-5e03-49e3-aff3-6604bed83fdb share btn then i will merge
> > 
> > 
> > Boss i have figured it out and pls review it . Let me know if anything . Thank you
> 
> run : npm run build the deployment got errors

sir i dont know why did this happen . i just changed logos . You can verify the things which i changed

**Comment by TejasNasre** [comment]
solve error if i check i will not merge this PR

**Comment by vedhcet-07** [comment]
sir i dk why it happened . but i will try again . give me some time . i will do from beginning again.

**Pull request closed without merging**
