### PR TITLE
Add Event Active Badge Logic and Database Support for Registration Status

### PR DESCRIPTION
**Pull request by Ryadav0654**
**Title**: Add **Event Active** Badge Logic and Database Support for Registration Status

### fix: #174 

1. **Event Active Badge Logic**:  
   - Implements conditional rendering of an "Event Active" badge based on the registration status of each event.
   - Enhances the `checkRegistrationStatus` function to set the badge according to real-time registration status, categorized as "Upcoming," "Active," or "Inactive."
   - Adds a filter button for users to toggle the display of active events, making it easier to view only those with open registration.
   
2. **Database Adjustments**:
   - Updates the handling of event start and end times to ensure consistency in time zone (UTC), while converting to local time on the client side.
   - Ensures new database entries related to registration timings are managed correctly to reflect accurate time information and provide seamless integration with client-side filtering.
   - Database fields (`event_registration_startdate` and `event_registration_enddate`) are stored in UTC without time zone to avoid discrepancies and ensure cross-timezone compatibility.

**Key Changes**:
- Added conditional logic for the "Event Active" badge in the event card component.
- Updated the `checkRegistrationStatus` function to toggle badge states based on current time relative to event registration dates.
- Applied client-side handling to fetch events that meet active registration criteria, helping users quickly see open events.
- Adjusted database model for `event_registration_startdate` and `event_registration_enddate` to `timestamp without time zone` for consistent time handling.

**Testing**:
- Verified that events display the correct badge status according to their registration times.
- Tested filtering feature to ensure "Event Active" toggle functions as expected.
- Confirmed that database time adjustments prevent discrepancies between displayed times and stored UTC times.

[Screencast from 2024-10-25 12-09-47.webm](https://github.com/user-attachments/assets/2ff0ec52-4df3-4e54-8bff-0b3729bc19f6)

### CODE REVIEW

**Comment by Ryadav0654** [comment]
Hi @Kishan-Ved ,
I have created this pull request. Could you please review the changes when you have time? Your feedback would be appreciated!
Thanks!

**Comment by TejasNasre** [comment]
Screenshot_2024-10-25-19-09-11-11
Fix it ser

**Comment by Ryadav0654** [comment]
> Screenshot_2024-10-25-19-09-11-11 Fix it ser

fixed it

**Comment by TejasNasre** [comment]
i will review tomorrow

**Comment by TejasNasre** [comment]
great sir will give you level 3 just change the branch to dev and don't close PR i need some time i am busy a bit

**Comment by Ryadav0654** [comment]
@TejasNasre Thank you for merging the PR! I appreciate the opportunity and look forward to contributing more in the future.

**Pull request merged**
