### PR TITLE
For Issue #9: Add toasts / pop-ups

### PR DESCRIPTION
**Pull request by Eshan05**
Added error and success toasts in the following routes
```graphql
- add-event-space
- explore-event-space
  - [spaceId]
- add-event
- manage-event
- register-event
  - [registerId]
- update-event
```

A simple preview:
7b84igAzC2

Made sure that the toasts are nice and visible, can stack and easy to modify for later. Also, they aren't that intrusive so the user won't be overwhelmed with them nor are they appearing for every single action only the main ones. They also match your existing UI

(PS: Due to the auto-format some tailwind classes got rearranged)

### CODE REVIEW

**Comment by Eshan05** [comment]
This is on mobile
firefox_fCjiMorndb

**Comment by TejasNasre** [comment]
Bro I told you to add this at the top let's see preview

**Comment by Eshan05** [comment]
> Bro I told you to add this at the top let's see preview 

I commented about it on the issue and you said "Okay" so I went with it, but I'll make changes if you want

**Comment by TejasNasre** [comment]
No worries

**Comment by TejasNasre** [comment]
I will merge in soon something is wrong in auth

**Comment by Eshan05** [comment]
> No worries 

If you feel like changing it later to something different if you change up your UI it's easily doable too

```
// Available positions:
// top-left, top-center, top-right, bottom-left, bottom-center, bottom-right
<Toaster position="top-center" />
```

**Comment by Eshan05** [comment]
> I will merge in soon something is wrong in auth

Yep ok no worries

**Comment by TejasNasre** [comment]
@Eshan05 Please make PR to dev branch

**Comment by Eshan05** [comment]
> @Eshan05 Please make PR to dev branch

Ok changed the base branch

**Comment by AKSHITHA-CHILUKA** [comment]
add level labels @TejasNasre 

Regards,
Community Manager Gssoc-ext

**Pull request merged**
