### PR TITLE
solved issue #5 Add Real questions to in FAQ

### PR DESCRIPTION
**Pull request by aasiflm10**
Added following questions in FAQ : 
What is NexMeet?
NexMeet is your go-to platform for organizing college and social events. NexMeet makes it super easy to plan, manage, and enjoy. We're all about bringing people together and making event planning fun and hassle-free!

How do I register for Events?
Browse events on the "Explore Events" tab, click "Register," and fill in the details to sign up. Now, all you have to do is show up and have fun!

Where can I view the events I've registered for?
Sign in, go to your profile, and view all your registered events under "Your Events."

Can I create my own custom events?
Yes, go to your profile, click "Organize Your Own Event," and fill in the details. You are ready to go!

How do I cancel my event registration?
Go to "Your Events" in Profile, select the event, and click "Cancel Registration."

Can I edit the details of my event after it's created?
Yes! You can update your event details anytime using "Manage your Events" in Profile section.

Is there a way to invite my friends to an event?
Yes, click the share button on the event page to invite friends via social media or link.

image

### CODE REVIEW

**Comment by TejasNasre** [comment]
Merge with dev

**Comment by aasiflm10** [comment]
> Merge with dev

merged with dev. Please check.

**Comment by TejasNasre** [comment]
Screenshot_2024-10-02-15-02-43-10
Solve this errors

**Comment by aasiflm10** [comment]
> Screenshot_2024-10-02-15-02-43-10 Solve this errors

working on it.

**Pull request merged**
