### PR TITLE
Add seprate contributor page #24

### PR DESCRIPTION
**Pull request by 0xSaurabhx**
- made it responsive for mobile as well
- add github token to increase github api rate limits

This is PR for #24

### CODE REVIEW

**Comment by TejasNasre** [comment]
@0xSaurabhx make PR to dev bro

**Comment by 0xSaurabhx** [comment]
> @0xSaurabhx make PR to dev bro fast

done

**Comment by 0xSaurabhx** [comment]
will you merge or u want me change

**Comment by TejasNasre** [comment]
> will you merge or u want me change

Update it and then I will merge it's easy just few min of work do it

**Pull request closed without merging**
