### PR TITLE
Added Explore community page in frontend + Database request to save/view/delete/edit new community information

### LINKED ISSUE #230: Add Community Listing Page
- Add Community Listing Page Like A Explore Event Page

- The Community Should First Approve By Super Admin 

- First Exposed The Route To Add Community
- Take Some Good Info About There Community And Take Relevant Info
- The User Can Join There Community Pages By Submitting User Info

### PR DESCRIPTION
**Pull request by mehul-m-prajapati**
fixes #230 

- Added new community page under explore community
- Implemented Add new community form to submit new community info
- Added a join button for users to join the community
- Added Database calls to save all community data and view the same in cards
- Added SQL function to update user counter in community table and RPC call in front-end to trigger the same

**TBD**: Add social media links for joining ???

### New Table Schema
```
-- Create communities table
create table communities (
  id uuid primary key default uuid_generate_v4(), -- Unique ID for each community
  community_name text not null, -- Name of the community
  community_description text, -- Short description of the community
  community_location text, -- Location or region where the community is based
  community_category text, -- Category of the community (e.g., Tech, Sports, Music)
  community_members_count integer default 0, -- Number of members in the community
  community_likes integer default 0, -- Number of likes the community has
  community_image text, -- URL of the community image
  community_creation_date timestamp with time zone default current_timestamp -- Date when the community was created
  is_approved boolean DEFAULT false -- Approval status of the community (false by default)
);

```

https://github.com/user-attachments/assets/3500efc2-c3dc-4089-90e8-a58f96f3f34f

--

### CODE REVIEW

**Comment by mehul-m-prajapati** [comment]
NOTE: Super admin & other features related to community will be done in the new PR

**Comment by mehul-m-prajapati** [comment]
@TejasNasre : please review the same

**Comment by TejasNasre** [comment]
sir add community wala page different hona

**Comment by TejasNasre** [comment]
and the joined community wala form ny hona bs whatsapp ke ya fir un ke discord server ke link hona

**Comment by mehul-m-prajapati** [comment]
@TejasNasre - give me list of form fields for add community page

**Comment by TejasNasre** [comment]
sir i am merging this pr after that i will make required changes

**Comment by mehul-m-prajapati** [comment]
Okay, we can do changes afterwards

**Comment by mehul-m-prajapati** [comment]
@TejasNasre : I have removed Join Community modal.

You can merge this PR. We can modify the page in new issue.

**Comment by aslams2020** [comment]
This PR has been merged by the GSSoC team 
here - https://github.com/sanjay-kv/Open-source-Practice/pull/1463

## Don't add labels to it now.

You'll get the points in the leaderboard update.

**Comment by TejasNasre** [comment]
sir please change LEARN.md with instruction to setup the things with storage also

**Pull request merged**
